app_env: development

server:
  port: 8080

database:
  driver: firebase
  host: localhost
  port: 5432
  name: exercises
  user: user
  password: password
  sslmode: disable
  max_open_connections: 10
  max_idle_connections: 5
  connection_max_lifetime: 30m
  connection_timeout: 5s
  auto_migrate: true

  postgres:
    schema: public
    search_path: public
    sslcert: ""
    sslkey: ""
    sslrootcert: ""

# Firebase (env-based). Prefer setting in .env
# FIREBASE_PROJECT_ID: your-project-id
# FIREBASE_CREDENTIALS_FILE: path/to/service-account.json
# For ADC, you can also set GOOGLE_APPLICATION_CREDENTIALS to point to the service account JSON.
# See: https://firebase.google.com/docs/admin/setup/#go
